//! POSIX syscall dispatch table.

use crate::syscall::errno::{err, Errno, SysResult};
use crate::syscall::handlers;
use crate::syscall::nr::*;

pub type SyscallFn = fn(u64, u64, u64, u64, u64, u64) -> SysResult;

pub fn dispatch(nr: u64, a0: u64, a1: u64, a2: u64, a3: u64, a4: u64, a5: u64) -> SysResult {
    match nr {
        SYS_READ => handlers::sys_read(a0, a1, a2, a3, a4, a5),
        SYS_WRITE => handlers::sys_write(a0, a1, a2, a3, a4, a5),
        SYS_OPEN => handlers::sys_open(a0, a1, a2, a3, a4, a5),
        SYS_CLOSE => handlers::sys_close(a0, a1, a2, a3, a4, a5),
        SYS_LSEEK => handlers::sys_lseek(a0, a1, a2, a3, a4, a5),
        SYS_BRK => handlers::sys_brk(a0, a1, a2, a3, a4, a5),
        SYS_MMAP => handlers::sys_mmap(a0, a1, a2, a3, a4, a5),
        SYS_MPROTECT => handlers::sys_mprotect(a0, a1, a2, a3, a4, a5),
        SYS_MUNMAP => handlers::sys_munmap(a0, a1, a2, a3, a4, a5),
        SYS_PIPE => handlers::sys_pipe(a0, a1, a2, a3, a4, a5),
        SYS_STAT => handlers::sys_stat(a0, a1, a2, a3, a4, a5),
        SYS_FSTAT => handlers::sys_fstat(a0, a1, a2, a3, a4, a5),
        SYS_IOCTL => handlers::sys_ioctl(a0, a1, a2, a3, a4, a5),
        SYS_ACCESS => handlers::sys_access(a0, a1, a2, a3, a4, a5),
        SYS_UNLINK => handlers::sys_unlink(a0, a1, a2, a3, a4, a5),
        SYS_READLINK => handlers::sys_readlink(a0, a1, a2, a3, a4, a5),
        SYS_GETCWD => handlers::sys_getcwd(a0, a1, a2, a3, a4, a5),
        SYS_CHDIR => handlers::sys_chdir(a0, a1, a2, a3, a4, a5),
        SYS_FCNTL => handlers::sys_fcntl(a0, a1, a2, a3, a4, a5),
        SYS_NANOSLEEP => handlers::sys_nanosleep(a0, a1, a2, a3, a4, a5),
        SYS_UNAME => handlers::sys_uname(a0, a1, a2, a3, a4, a5),
        SYS_GETUID => handlers::sys_getuid(a0, a1, a2, a3, a4, a5),
        SYS_GETEUID => handlers::sys_geteuid(a0, a1, a2, a3, a4, a5),
        SYS_GETGID => handlers::sys_getgid(a0, a1, a2, a3, a4, a5),
        SYS_GETEGID => handlers::sys_getegid(a0, a1, a2, a3, a4, a5),
        SYS_ARCH_PRCTL => handlers::sys_arch_prctl(a0, a1, a2, a3, a4, a5),
        SYS_SET_TID_ADDRESS => handlers::sys_set_tid_address(a0, a1, a2, a3, a4, a5),
        SYS_EXIT_GROUP => handlers::sys_exit_group(a0, a1, a2, a3, a4, a5),
        SYS_GETDENTS64 => handlers::sys_getdents64(a0, a1, a2, a3, a4, a5),
        SYS_CLOCK_GETTIME => handlers::sys_clock_gettime(a0, a1, a2, a3, a4, a5),
        SYS_OPENAT => handlers::sys_openat(a0, a1, a2, a3, a4, a5),
        SYS_PIPE2 => handlers::sys_pipe2(a0, a1, a2, a3, a4, a5),
        SYS_MKFIFO => handlers::sys_mkfifo(a0, a1, a2, a3, a4, a5),
        SYS_MSGGET => handlers::sys_msgget(a0, a1, a2, a3, a4, a5),
        SYS_MSGSND => handlers::sys_msgsnd(a0, a1, a2, a3, a4, a5),
        SYS_MSGRCV => handlers::sys_msgrcv(a0, a1, a2, a3, a4, a5),
        SYS_MSGCTL => handlers::sys_msgctl(a0, a1, a2, a3, a4, a5),
        SYS_SHMGET => handlers::sys_shmget(a0, a1, a2, a3, a4, a5),
        SYS_SHMAT => handlers::sys_shmat(a0, a1, a2, a3, a4, a5),
        SYS_SHMDT => handlers::sys_shmdt(a0, a1, a2, a3, a4, a5),
        SYS_SHMCTL => handlers::sys_shmctl(a0, a1, a2, a3, a4, a5),
        SYS_FUTEX => handlers::sys_futex(a0, a1, a2, a3, a4, a5),
        SYS_DUP => handlers::sys_dup(a0, a1, a2, a3, a4, a5),
        SYS_DUP2 => handlers::sys_dup2(a0, a1, a2, a3, a4, a5),
        SYS_GETPID => handlers::sys_getpid(a0, a1, a2, a3, a4, a5),
        SYS_GETPPID => handlers::sys_getppid(a0, a1, a2, a3, a4, a5),
        SYS_SOCKET => handlers::sys_socket(a0, a1, a2, a3, a4, a5),
        SYS_BIND => handlers::sys_bind(a0, a1, a2, a3, a4, a5),
        SYS_LISTEN => handlers::sys_listen(a0, a1, a2, a3, a4, a5),
        SYS_ACCEPT => handlers::sys_accept(a0, a1, a2, a3, a4, a5),
        SYS_CONNECT => handlers::sys_connect(a0, a1, a2, a3, a4, a5),
        SYS_SENDTO => handlers::sys_sendto(a0, a1, a2, a3, a4, a5),
        SYS_RECVFROM => handlers::sys_recvfrom(a0, a1, a2, a3, a4, a5),
        SYS_FORK => handlers::sys_fork(a0, a1, a2, a3, a4, a5),
        SYS_CLONE => handlers::sys_clone(a0, a1, a2, a3, a4, a5),
        SYS_EXECVE => handlers::sys_execve(a0, a1, a2, a3, a4, a5),
        SYS_EXIT => handlers::sys_exit(a0, a1, a2, a3, a4, a5),
        SYS_WAIT4 => handlers::sys_wait4(a0, a1, a2, a3, a4, a5),
        SYS_KILL => handlers::sys_kill(a0, a1, a2, a3, a4, a5),
        SYS_RT_SIGACTION | SYS_SIGNAL => handlers::sys_rt_sigaction(a0, a1, a2, a3, a4, a5),
        SYS_RT_SIGPROCMASK => handlers::sys_rt_sigprocmask(a0, a1, a2, a3, a4, a5),
        SYS_RT_SIGRETURN => handlers::sys_rt_sigreturn(a0, a1, a2, a3, a4, a5),
        SYS_PRCTL => handlers::sys_prctl(a0, a1, a2, a3, a4, a5),
        _ => err(Errno::ENOSYS),
    }
}
